services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  
  rabbitmq:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 5
  
  auction-svc:
    image: korban910/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${DOCKER_ASPNETCORE_URLS}
      - RABBITMQ_HOST=${RABBITMQ_HOST_NAME}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - AUCTION_DATABASE=${DOCKER_AUCTION_DATABASE}
      - IDENTITY_URL=${DOCKER_IDENTITY_URL}
      - CLAIM_USER_NAME=${DOCKER_CLAIM_USER_NAME}
      - AUCTION_MASS_PREFIX=${AUCTION_MASS_PREFIX}
    ports:
      - "7001:80"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  search-svc:
    image: korban910/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${DOCKER_ASPNETCORE_URLS}
      - RABBITMQ_HOST=${RABBITMQ_HOST_NAME}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SEARCH_DATABASE=${DOCKER_SEARCH_DATABASE}
      - SEARCH_DATABASE_NAME=${SEARCH_DATABASE_NAME}
      - IDENTITY_URL=${DOCKER_IDENTITY_URL}
      - CLAIM_USER_NAME=${DOCKER_CLAIM_USER_NAME}
      - AUCTION_URL=${DOCKER_AUCTION_URL}
      - SEARCH_MASS_PREFIX=${SEARCH_MASS_PREFIX}
    ports:
      - "7002:80"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    
  identity-svc:
    image: korban910/identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_DOCKER_ENVIRONMENT}
      - ASPNETCORE_URLS=${DOCKER_ASPNETCORE_URLS}
      - IDENTITY_DATABASE=${DOCKER_IDENTITY_DATABASE}
      - APP_SCOPE=${APP_SCOPE}
      - DISPLAY_NAME=${DISPLAY_NAME}
      - POSTMAN_CLIENT_ID=${POSTMAN_CLIENT_ID}
      - POSTMAN_CLIENT_NAME=${POSTMAN_CLIENT_NAME}
      - OPEN_ID_SCOPE=${OPEN_ID_SCOPE}
      - PROFILE_SCOPE=${PROFILE_SCOPE}
      - POSTMAN_REDIRECTURI=${POSTMAN_REDIRECTURI}
      - POSTMAN_SECRET=${POSTMAN_SECRET}
      - NEXT_APP_ID=${NEXT_APP_ID}
      - NEXT_CLIENT_NAME=${NEXT_CLIENT_NAME}
      - NEXT_SECRET=${NEXT_SECRET}
      - NEXT_REDIRECTURI=${NEXT_REDIRECTURI}
      - CLAIM_USER_NAME=${CLAIM_USER_NAME}
      - ISSUER_URI=${IDENTITY_URL}
      - ASPNETCORE_DOCKER_ENVIRONMENT=${ASPNETCORE_DOCKER_ENVIRONMENT}
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
      
  gateway-svc:
    image: korban910/gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_DOCKER_ENVIRONMENT}
      - ASPNETCORE_URLS=${DOCKER_ASPNETCORE_URLS}
      - IDENTITY_URL=${DOCKER_IDENTITY_URL}
      - CLAIM_USER_NAME=${CLAIM_USER_NAME}
      - AUCTION_CLUSTER_ID=${AUCTION_CLUSTER_ID}
      - SEARCH_CLUSTER_ID=${SEARCH_CLUSTER_ID}
      - AUCTION_URL=${DOCKER_AUCTION_URL}
      - SEARCH_URL=${DOCKER_SEARCH_URL}
    ports:
      - "6001:80"
    
volumes:
  pgdata:
  mongodata: