import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/nav/NavBar";
import ToasterProvider from "@/app/providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Car Auctions",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body>
        <ToasterProvider />
        <NavBar />
        <main className="container mx-auto px-5 pt-10">
          {children}
        </main>
      </body>
    </html>
  );
}

export default RootLayout;