import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/app/nav/NavBar";
import ToasterProvider from "@/app/providers/ToasterProvider";
import SignalRProvider from "@/app/providers/SignalRProvider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Car Auctions",
  description: "Generated by create next app",
};

// Below force to not catch the app, and dynamic it
// export const dynamic = "force-dynamic";

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            <SignalRProvider>{children}</SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
};

export default RootLayout;
