apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  AUCTION_DATABASE: "${DOCKER_AUCTION_DATABASE}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_MASS_PREFIX: "${AUCTION_MASS_PREFIX}"
  GRPC_PORT: "${DOCKER_GRPC_PORT}"
  WEB_API_PORT: "${DOCKER_WEB_API_PORT}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  SEARCH_DATABASE: "${DOCKER_SEARCH_DATABASE}"
  SEARCH_DATABASE_NAME: "${SEARCH_DATABASE_NAME}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_URL: "${DOCKER_AUCTION_URL}"
  SEARCH_MASS_PREFIX: "${SEARCH_MASS_PREFIX}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  BIDDING_DATABASE: "${DOCKER_BID_DATABASE}"
  BIDDING_DATABASE_NAME: "${BIDDING_DATABASE_NAME}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_URL: "${DOCKER_AUCTION_URL}"
  BID_MASS_PREFIX: "${BID_MASS_PREFIX}"
  GRPC_URL: "${DOCKER_GRPC_URL}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${CLAIM_USER_NAME}"
  AUCTION_CLUSTER_READ: "${AUCTION_CLUSTER_READ}"
  AUCTION_CLUSTER_WRITE: "${AUCTION_CLUSTER_WRITE}"
  AUCTION_CLUSTER_ID: "${AUCTION_CLUSTER_ID}"
  SEARCH_CLUSTER_READ: "${SEARCH_CLUSTER_READ}"
  SEARCH_CLUSTER_ID: "${SEARCH_CLUSTER_ID}"
  BIDS_CLUSTER_READ: "${BIDS_CLUSTER_READ}"
  BIDS_CLUSTER_WRITE: "${BIDS_CLUSTER_WRITE}"
  BIDS_CLUSTER_ID: "${BIDS_CLUSTER_ID}"
  NOTIFICATION_CLUSTER: "${NOTIFICATION_CLUSTER}"
  NOTIFICATION_CLUSTER_ID: "${NOTIFICATION_CLUSTER_ID}"
  AUCTION_URL: "${DOCKER_AUCTION_URL}"
  AUCTION_API: "${AUCTION_API}"
  SEARCH_URL: "${DOCKER_SEARCH_URL}"
  SEARCH_API: "${SEARCH_API}"
  BIDS_URL: "${DOCKER_BIDDING_URL}"
  BIDS_API: "${BIDS_API}"
  NOTIFICATION_API: "${NOTIFICATION_API}"
  NOTIFICATION_URL: "${DOCKER_NOTIFICATION_URL}"
  AUTHORIZATION_POLICY: "${AUTHORIZATION_POLICY}"
  CUSTOM_POLICY: "${CUSTOM_POLICY}"
  CLIENT_APP: "${CLIENT_APP_HOST}"
  VIRTUAL_HOST: "${GATEWAY_VIRTUAL_HOST}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  IDENTITY_DATABASE: "${DOCKER_IDENTITY_DATABASE}"
  APP_SCOPE: "${APP_SCOPE}"
  DISPLAY_NAME: "${DISPLAY_NAME}"
  POSTMAN_CLIENT_ID: "${POSTMAN_CLIENT_ID}"
  POSTMAN_CLIENT_NAME: "${POSTMAN_CLIENT_NAME}"
  OPEN_ID_SCOPE: "${OPEN_ID_SCOPE}"
  PROFILE_SCOPE: "${PROFILE_SCOPE}"
  POSTMAN_REDIRECTURI: "${POSTMAN_REDIRECTURI}"
  POSTMAN_SECRET: "${POSTMAN_SECRET}"
  NEXT_APP_ID: "${NEXT_APP_ID}"
  NEXT_CLIENT_NAME: "${NEXT_CLIENT_NAME}"
  NEXT_SECRET: "${NEXT_SECRET}"
  NEXT_REDIRECTURI: "${DOCKER_NEXT_REDIRECTURI_HOST}"
  CLAIM_USER_NAME: "${CLAIM_USER_NAME}"
  ISSUER_URI: "${IDENTITY_URL_HOST}"
  ASPNETCORE_DOCKER_ENVIRONMENT: "${ASPNETCORE_DOCKER_ENVIRONMENT}"
  VIRTUAL_HOST: "${IDENTITY_VIRTUAL_HOST}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-svc-config
data:
  AUTH_SECRET: "${AUTH_SECRET}"
  NEXT_PUBLIC_AUTH_DUENDE_IDENTITY_SERVER6_ID: "${NEXT_PUBLIC_AUTH_DUENDE_IDENTITY_SERVER6_ID}"
  AUTH_DUENDE_IDENTITY_SERVER6_CLIENT_ID: "${AUTH_DUENDE_IDENTITY_SERVER6_CLIENT_ID}"
  AUTH_DUENDE_IDENTITY_SERVER6_SECRET: "${AUTH_DUENDE_IDENTITY_SERVER6_SECRET}"
  AUTH_DUENDE_IDENTITY_SERVER6_ISSUER: "${AUTH_DUENDE_IDENTITY_SERVER6_ISSUER_HOST}"
  AUTH_DUENDE_IDENTITY_SERVER6_SCOPE: "${AUTH_DUENDE_IDENTITY_SERVER6_SCOPE}"
  AUTH_DUENDE_IDENTITY_SERVER6_ISSUER_INTERNAL: "${AUTH_DUENDE_IDENTITY_SERVER6_ISSUER_INTERNAL}"
  NEXT_INTERNAL_BASE_URL: "${NEXT_INTERNAL_BASE_URL}"
  NEXT_PUBLIC_BASE_URL: "${NEXT_PUBLIC_BASE_URL_HOST}"
  AUTH_URL: "${AUTH_URL_HOST}"
  AUTH_URL_INTERNAL: "${AUTH_URL_INTERNAL}"
  VIRTUAL_HOST: "${WEBAPP_VIRTUAL_HOST}"
  VIRTUAL_PORT: "${WEBAPP_VIRTUAL_PORT}"
  