apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  AUCTION_DATABASE: "${DOCKER_AUCTION_DATABASE}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_MASS_PREFIX: "${AUCTION_MASS_PREFIX}"
  GRPC_PORT: "${DOCKER_GRPC_PORT}"
  WEB_API_PORT: "${DOCKER_WEB_API_PORT}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  SEARCH_DATABASE: "${DOCKER_SEARCH_DATABASE}"
  SEARCH_DATABASE_NAME: "${SEARCH_DATABASE_NAME}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_URL: "${DOCKER_AUCTION_URL}"
  SEARCH_MASS_PREFIX: "${SEARCH_MASS_PREFIX}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bid-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  BIDDING_DATABASE: "${DOCKER_BID_DATABASE}"
  BIDDING_DATABASE_NAME: "${BIDDING_DATABASE_NAME}"
  IDENTITY_URL: "${DOCKER_IDENTITY_URL}"
  CLAIM_USER_NAME: "${DOCKER_CLAIM_USER_NAME}"
  AUCTION_URL: "${DOCKER_AUCTION_URL}"
  BID_MASS_PREFIX: "${BID_MASS_PREFIX}"
  GRPC_URL: "${DOCKER_GRPC_URL}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notify-svc-config
data:
  ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
  ASPNETCORE_URLS: "${DOCKER_ASPNETCORE_URLS}"
  RABBITMQ_HOST: "${RABBITMQ_HOST_NAME}"
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  